### ISSUE TITLE
Getting error "_pickle.UnpicklingError: invalid load key, 'v'."

### ISSUE THREAD

**Issue by iamshreeji-copy1** [yochaiye/LipVoicer#7]
**Dear Author,

Can you help to decode this error (already loaded the pre-trained model at the given path), Is it issue due to the model file format or anything else!

Thanks in advance for your attention.

Regards,
Ravi**

_____

(lipvoicer3.8_env) linux@linux:~/Documents/ravi_phd/lipvoicer/LipVoicer$ python3.8 inference_real_video.py
/home/linux/miniconda3/envs/lipvoicer3.8_env/lib/python3.8/site-packages/ctcdecode/_ext/ctc_decode.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZNK2at10TensorBase16mutable_data_ptrIiEEPT_v
melgen:
  _name_: melgen
  in_channels: 80
  out_channels: 80
  diffusion_step_embed_dim_in: 128
  diffusion_step_embed_dim_mid: 512
  diffusion_step_embed_dim_out: 512
  res_channels: 512
  skip_channels: 512
  num_res_layers: 12
  dilation_cycle: 1
  mel_upsample:
  - 2
  - 2
diffusion:
  T: 400
  beta_0: 0.0001
  beta_T: 0.02
  beta: null
dataset:
  videos_dir: datasets/LRS3/videos
  mouthrois_dir: datasets/LRS3/mouth_crops
  audios_dir: datasets/LRS3/audios
  sampling_rate: ${audio.sampling_rate}
  videos_window_size: 25
  audio_stft_hop: ${audio.hop_length}
audio:
  sampling_rate: 16000
  filter_length: 640
  hop_length: 160
  win_length: 640
  mel_fmin: 20.0
  mel_fmax: 8000.0
train:
  name: LRS3
  save_dir: null
  ckpt_iter: max
  iters_per_ckpt: 10000
  iters_per_logging: 100
  n_iters: 1000001
  learning_rate: 0.0002
  batch_size_per_gpu: 8
generate:
  name: LRS3
  ckpt_path: exp/LRS3/wnet_h512_d12_T400_betaT0.02/checkpoint/1000000.pkl
  n_samples: 3
  video_path: /home/linux/Documents/ravi_phd/lipvoicer/LipVoicer/bbc_video.mp4
  w_video: 2
  w_asr: 1.5
  asr_start: 270
  save_dir: /home/linux/Documents/ravi_phd/lipvoicer/LipVoicer/generated_bbc_video.mp4
  lipread_text_dir: null
distributed:
  dist_backend: nccl
  dist_url: tcp://localhost:54321

Lipreading configuration file loaded.
AudioVisualModel Parameters: 57.309632M
Successfully loaded MelGen checkpoint
saving to output directory /home/linux/Documents/ravi_phd/lipvoicer/LipVoicer/generated_bbc_video.mp4/bbc_video
Loading ASR, tokenizer and decoder
Rank 0: Model loaded at step 12720
Rank 0: Model loaded at step 0
saving to output directory /home/linux/Documents/ravi_phd/lipvoicer/LipVoicer/generated_bbc_video.mp4/bbc_video/w1=2_w2=1.5_asr_start=270
Cropping lip region and predicting text
Cropping mouth region
[2024-12-25 20:05:17,510][root][INFO] - reading a config file from mouthroi_processing/benchmarks/LRS3/language_models/lm_en_subword/model.json
[2024-12-25 20:05:17,710][root][INFO] - Tie weights set to False
[2024-12-25 20:05:17,710][root][INFO] - Dropout set to 0.0
[2024-12-25 20:05:17,710][root][INFO] - Emb Dropout set to 0.0
[2024-12-25 20:05:17,710][root][INFO] - Att Dropout set to 0.0
Error executing job with overrides: []
Traceback (most recent call last):
  File "inference_real_video.py", line 278, in <module>
    main()
  File "/home/linux/miniconda3/envs/lipvoicer3.8_env/lib/python3.8/site-packages/hydra/main.py", line 94, in decorated_main
    _run_hydra(
  File "/home/linux/miniconda3/envs/lipvoicer3.8_env/lib/python3.8/site-packages/hydra/_internal/utils.py", line 394, in _run_hydra
    _run_app(
  File "/home/linux/miniconda3/envs/lipvoicer3.8_env/lib/python3.8/site-packages/hydra/_internal/utils.py", line 457, in _run_app
    run_and_report(
  File "/home/linux/miniconda3/envs/lipvoicer3.8_env/lib/python3.8/site-packages/hydra/_internal/utils.py", line 223, in run_and_report
    raise ex
  File "/home/linux/miniconda3/envs/lipvoicer3.8_env/lib/python3.8/site-packages/hydra/_internal/utils.py", line 220, in run_and_report
    return func()
  File "/home/linux/miniconda3/envs/lipvoicer3.8_env/lib/python3.8/site-packages/hydra/_internal/utils.py", line 458, in <lambda>
    lambda: hydra.run(
  File "/home/linux/miniconda3/envs/lipvoicer3.8_env/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 132, in run
    _ = ret.return_value
  File "/home/linux/miniconda3/envs/lipvoicer3.8_env/lib/python3.8/site-packages/hydra/core/utils.py", line 260, in return_value
    raise self._return_value
  File "/home/linux/miniconda3/envs/lipvoicer3.8_env/lib/python3.8/site-packages/hydra/core/utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
  File "inference_real_video.py", line 270, in main
    generate(
  File "/home/linux/miniconda3/envs/lipvoicer3.8_env/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "inference_real_video.py", line 198, in generate
    mouthroi, text = crop_and_infer.main(generate_cfg["video_path"], output_directory)
  File "/home/linux/Documents/ravi_phd/lipvoicer/LipVoicer/mouthroi_processing/crop_and_infer.py", line 45, in main
    pipeline = InferencePipeline(config_filename, device='cuda', detector=detector, face_track=True)
  File "/home/linux/Documents/ravi_phd/lipvoicer/LipVoicer/mouthroi_processing/pipelines/pipeline.py", line 52, in __init__
    self.landmarks_detector = LandmarksDetector(device="cuda:0")
  File "/home/linux/Documents/ravi_phd/lipvoicer/LipVoicer/mouthroi_processing/pipelines/detectors/retinaface/detector.py", line 16, in __init__
    self.face_detector = RetinaFacePredictor(
  File "/home/linux/Documents/ravi_phd/lipvoicer/face_detection/ibug/face_detection/retina_face/retina_face_predictor.py", line 28, in __init__
    pretrained_dict = torch.load(model.weights, map_location=self.device)
  File "/home/linux/miniconda3/envs/lipvoicer3.8_env/lib/python3.8/site-packages/torch/serialization.py", line 795, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/linux/miniconda3/envs/lipvoicer3.8_env/lib/python3.8/site-packages/torch/serialization.py", line 1002, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.

**Comment by yochaiye** [comment]
It seems like the loading of weights of the Retina Face Detector model is unsuccessful.
Are you sure that you followed the installation instructions of RetinaFace closely?

**Comment by beria-moon** [comment]
I have done ' pip install retina-face' in my cuda envs, but i still meet the same error as [iamshreeji-copy1]?

**Comment by beria-moon** [comment]
I save the problem by redownload the face_detection and  face_alignment , replace 'git clone https://github.com/hhj1897/face_detection.git'. with  'git lfs clone https://github.com/hhj1897/face_detection.git''

**Comment by yochaiye** [comment]
@beria-moon , thank you for the update, glad you've sorted it.
Strange though, for me it worked with the original flow provided in the `README` file
